- name: install docker-ce
  block:
    - name: docker-ce - deploy ppa gpg key 
      ansible.builtin.blockinfile:
        path: /etc/apt/trusted.gpg.d/docker-ce.asc
        create: true
        block: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Comment: Hostname: 
          Version: Hockeypuck 2.1.0-223-gdc2762b

          xsFNBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
          lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
          38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
          L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
          UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
          cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
          ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
          vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
          G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
          XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
          q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
          zStEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+wsF3
          BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
          v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
          tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
          jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
          6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
          XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
          FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
          g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
          ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
          9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
          G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
          FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymwsDzBBABCgAd
          FiEEVossLDZVyg9kiiNzLcMego6bon8FAlrW9O8ACgkQLcMego6bon+GkQwAuV+J
          MdoB4dIzd/hmkhNIvlMxyQeAZtEtjtC/34CKf6XSFeilc/LaDit6UR+q7rapqzrA
          mRTQBgGE58JaTGWqUcvdeqn/jHZY6CmE4A/m1mXebrkExIZDaCZnUKvjrnd7ykAZ
          1LvCCHBqytL842EVRfgHP2FK3FuG/S+q3d3R2z7NrtoDAq1kGU68OlQbglDE86EB
          voQA0Ivz7bvY6J27UbDhH2ktE6Z9t6LJMTTOAw3oiyC8w3m3eReAVUkKs4w7FKfs
          U4C/HVQiEVRdBLBKpxkYd2sK1QO+TivWbojnrD/zwq+ZGyhrS0J3Jou7I9+ZM9Nx
          bapqVSbL/AIsa5nNBZ+Ws3GDGWUAq6Q403/qjCUDQbwUFcN79xwvwG+5nrRpQG7A
          qci0iaF9chu3fps1y7eyDLe8B1kFRe+eNrtNsg9k4q49bTH4syEroFMlnCVBHYjE
          TFQNU9ScUd+ihwA/gF5kuaSf7i9J820rzdHVlZsA+2yPY//1fU5Li/5qyVycwsDz
          BBABCgAdFiEENviLv3qUXsqdNwpV7jp7QXCiQ/MFAlraBlYACgkQ7jp7QXCiQ/N1
          awv/QbQKE3WUi1dLwStpXcEiZ6Zt6eMb9zKAZe/z9O1+QFSbrP/3D+jHcXdJw/H6
          jMJBr9M48toelD3/O3LQyleKJUN9nJu3MJ1Zq5lqu+oOpMIW+Vupfp2BH5aSfPLt
          dLtOkwiPlHz4SvRDzN3rBLb4tviv+7Rb/ZfSoCAZH+K4Lpe8p4/C1/QgT+9tZlRw
          wXcYsxLtkpFQ8hBbu1AAZN2awuaYb4kqhE2fxy53uXQHBo4+B1iwbl9cS4QFBqjA
          kMzrrRdcjrQnM2mk7/2Bpcz31Mnavb5rc3ZWtDwCsNghd/P/S0SSZ6papGbfTYKV
          1aLNnPhOyq4TGO7M7bnH46R7Z7ohDklmxzqbwHFo1KfOd4jGa07z/AYpTR6IrATF
          9Fcz0ertZmwtMSoATTSDBmFJOBp+pv9J+lbIhogTt58W42zSxmXD/21sJ1FjGn6Q
          y89xY/xbRIB9pUIx10WqhQHmaHPE7IZ7ad9h9wRoqiONLdNl6R9ymKj8PTWC+P7A
          3O90wsBcBBABAgAGBQJa4LwIAAoJELpjAAzZ0FPL758IAIVHn9eMwtHLHaIbZ+tI
          JqD9nTAjcEn4Vpfe+onCs/t3DCSwvIUiU9aH0GcokKPs5CckdPDmS2vfq4m8/B8f
          WJj4aPgRLapzAz0DojbRSFSZdWPl3b3Zf2UkLNIaMAkjnM+AqiM6rrHMwUdq922P
          QMnzYhayrMKdPNftr32zdxL+h7PZRn57evdbmN5mrTNOK2ta2B/xfA7fvL1SqLqy
          4HJNF0fsxuNLPncebvhSLJi2FyZtKbG0NgMb3d1sIMmBJnrBkAL4ZRJuu5OnnYkh
          vn3m0N5f9LaIy3M64+YiccOR8dj6xq0dKdGEhxM9QC5XU8AaOksWe3YTcHKVTYt6
          omfCwVwEEAEKAAYFAlrkotQACgkQ90pg6wWlGpjd5Q/8DJM54FNxW3aKTzBS6urf
          Uy/c9jgDtOKWGXJ/X3IeWbFmSuA27lMnAwx9obcukeVjFuAGeabRCrc0qd6LV3oy
          PG95qMwhwXHdzXFzA5RzLlArRJtRgyESvYXT493m45TJQbpDkO8NHRbq/JtvXyBD
          AvfcfvNrd0newfp0gYIFvw0J36n5J1GQF9Klk+UJywmFkQN/gI1ZfD80FnEzS9wk
          NySBcGghXWtoeABppAIaNlFp4P7P2wUX15DMXSD2mbnI/lYZsrtl8rbTTMPNI0PT
          SqymMZv7RN0nLPOSdel1TlSUU31FER7Q1/OshWsvs1OKRnllv/ICkiZTfA1tmMYh
          TXVS19LurMufXL2Q6va7Es8zwj6dc3OO4YqBVu7Kjk84AwVHMWx+1aTjGzyMRNmW
          IyXVrZEz7GCO6WUUDw4ci1zAyCFNPDHVlEeeGSe+q+kPB87A4geAlyv8xJAe4QUD
          dV3D8ufhR1k/a+vcLDRv+T6QyVo8f59Y5jW/hcMx+/3jJ5AZcd0VGGWUaLuC1bWu
          Gz/6bjoRB2/rrprXXdff8dPyUBXjOB4mFDgZsOzh6j2tgeAEJKkmO1SMmh7RBMaE
          /4qGG2s77oFs8+1AsdXsbJLN0+v5XtO0P6RK77G6I/caM5kUIQc1WcSPLRj3vUB3
          u7f8NhpBsjWNd3G2QXDmHNPCwXMEEAEKAB0WIQTU/3wdYJFfOEC/1Ysr6KOtDiGt
          nQUCW1Yz0wAKCRAr6KOtDiGtnaL/D/9mnG8T+B2IPZKN+IKR8FQsVk8OJBKlGfPq
          M9pFDjQqtK4QJIi/0Mc0Iu/Bl4aYYbBdDu1s5JWNo/Ln1qznN97kRyyuWaV5bf1J
          IdjZ3Y52Uc+WW4+dJNVYgmYnwPGQEWs5SWBwCaD7gR2tFeAwNS1+5fdCSfAkVYEU
          QaJt9KNafT0fqrqlLWY+2CntDcOZlDI6nMm4GaginFlWldWxJzbYkmIlzpZuIbSI
          yLLy0k6FYkuQLLfWzFVrsmZzxAvLZQLIITY00MLHzk7EUvui8FRjT3PesNYIpEA8
          nqgiWnfr9RRnvnD3IzURUhP9p45lrlQmqnAOW3HfZabb3Fi+Oqks8a+yx114sVJL
          heRuKujpgMEPv8o5DSZF7XDUN9D2VfjsJnceJzBWiMdx48zc2jKJK2S1mizIm7ii
          YybzaZBKTlf2uAkNwiIduA/21KX9oQtqgGzp3Bq2wVzu8FLXdTrDu+FDE7UmAklE
          ClJfapo971QcPifZL8kTAWMaBvxZ8is8M30MaTcgJ7ZnNPelYUPefwWasjz2Mts7
          fAzM40HuaYjOkwlV3pRs0+rvUdLIFQGFL+sH/bQTaPKlp9kTtTGD7PTt56oCjs1f
          AQt1dHXhbcwREz3soIhoIiX0ecJdW3PolnKqL5FkppPJvcDepi/tc5L2YWHzAe5n
          JpJVRUf+9MLA8wQQAQoAHRYhBN1yvNOqGNMZplQT6mCcHG+/MujmBQJcEWdVAAoJ
          EGCcHG+/Mujm0b0MAJX+CjAtwt3pfEw9a2cbMr2MA+8rHh9XJO4FpC4f9H1CVqfN
          P5XtDOFKFlj9yRn6iiynxlC9JoA6/Db1DjvVMMqjLrQSvGjB99lapcWKuvpFkG1N
          lCqrV59RDJXGSRQ82ZSO0zmJ+hBZp3AKSLVLKbev0Hxjoy463pP27tKxLGDbvFtJ
          7ifo8LXN+7Sm0GuoMr1i9PyGf0AJ/t/SkyJ4AaNKZeGx8W8qggRv+dOTYPYbsBuv
          SjnMwf0JZQfIjn3ulTA7aY86lEVqNengepwefqYSiVPZCk1TldjQWRHrVvp7IICs
          4Q8ZpHDdIpyOCuKPBdgfWh2KxzDnKOY0g+FUAx3HPsa3ZKb3S5cuNNoo9uQwmOsr
          rNY1+Hx1qGh2kmfyDShRiqkIjD4KIbKvX0om2HmnlpTSVD00jQGF5kLcZYpWOy3l
          W4GsDZmA27hkbCIe2+LpIQ9MAf3SIcyuVMmB2+cKsSJA+NR0u18WPUtRY248vP17
          XMRUm7UyzuE+JaqdiMLA8wQQAQoAHRYhBBsT4JvvTkifV7wDLl6AozXqlXJOBQJc
          RYPxAAoJEF6AozXqlXJO4qkL/0rhK/cT97zl6vM4WfOwpMvWY+xvMUnpon4otlNe
          g39PIJr0pA67f5XfKYYEywlqid/jZ1td9QVBreLgeMuKrX3MDE8XlNGQ4r4THY9A
          SET+1KREldpCh02dWQu8AtMdqQS2MqbY0SZjOgJODK6DHX8rysHIePNxxzldniEH
          lQqA88UcypuBQH6xg9bDVKH2lMhRF6ZiLvwLpM/8bk7p42ykpJJi6deBXi13tSeq
          l1s4lYd/alu4n/tkDUXb7PCB/vIkaC8V6DUBAwKI3UeqK3hatIE/dU9vtJDkcfUZ
          07w7OAFQT0VyTjcVK+IFsDomReL+2xo27qoM1+/E6Bwl2qxcvomvkxfH7zAyzzIL
          TRRqGHOmIYRkAwwm48DK/HTOUbZP3Icg1cf5zd4PUdznXTBW9HIz6UeO7B1dEcb4
          KdJyZlJay1ar2Uy1/myI+ypYpfYapFQzmP8Ttt0PJKkgBAvcjRqu3bDLiJUBnQDy
          +h/TKqiULB6u9hKsi+wCO9lgv8LA8wQQAQoAHRYhBG6x+smNL3V7ujezlWdZ+62g
          TyaCBQJd261yAAoJEGdZ+62gTyaCSR0L/ikLm3GgjDzk1oFaMq623VPHj6UsRa+O
          E7WwcRGsd3F5kJIdFkA18EAn+kw/BGV214zuy0xYtcID8VAU4sOqrLdcugXK5h+T
          R3wFbi94ftnm17lUprPn/oM1ucbiU1/fTEQBu3BEWuS5fRGXNn36r7A5SztBtebp
          Qkb+pbF8plryRL+HCzDj9h5iI1K+E6NSqMS7g7ylsMmywqy7lH2HzxpKQwhPjjHa
          qmqUXTMOjQw/6B7QggTLQJ+7pk9o3+ljFDOd5YgBXlCX0vP6y7dtgjGFiguuhTIu
          vmujC6/qIX4gvJ+Rrt+szQxSCvtSXFbr1gKlvqpd3Ih79OrciRPqFdGRGP5Clz1/
          3J2gXaPbWAxv3j+GsZNA9w93wxWj6J/qKMZWfSkOOPBPQH9b+RUovKAUz/vCQM9M
          ckNMfn48KrT1wRz+CxNJiH4RGQj8NxeUSrfeEIkwh7MmITv+gMKTEYFgVu5pd8Pr
          0IEEe4hzZLhFN/4vCWWkAflKb0yPHmzHesLA8wQQAQgAHRYhBMk3sPZPMttZT0id
          V3qEjgpixsEJBQJhZqZOAAoJEHqEjgpixsEJLDMMAL6ADkwpPCl+UFLYaVOPEFmu
          OTtBJKIiwFpgwO/oClugjpVCE0CRk0lu6wjSFj0H9QNwQVYsdsZH+rogGV4vG7f6
          1ymplY3N5jPJoUXC27C5Z8/6yXwAD/d0lXgxWUsklGy7uiLjKciqZeY1B01u8BxL
          zwkaz5IgBJAyAEfNTEGgQwBPXNwZTRiA7IZOcToEffWXA6PQLL5MZItuPvQlepLb
          /Hk57mVbF36GKbBkR7119bz5FGdd/eYsV1Zghi0Ez/lxtHW5798+sHq/q8yHW1/V
          BzNWUwE1a8wh9nmIe23azv2KeeoQUa/c+6g1KZV1kKUHJxjcrBOgJoC0oNFAcat/
          IzZ7kHpfZyDJAbs7I9AOQpnx3wDLFYteCR57XxADq+C3yCu7GTl2J1joa7fcgy76
          KAD7adegz4/WYr9bUaqRaSBgYEsEGcgTdZdxsXqfN3h+KjSKe/SN2CvfeDaBXB60
          OWPYtn0eRjXdnz1YD2EB3iPYvbcV4SddEWHuewZHPsJ1BBAWCgAdFiEEQg1mjjOr
          soWzPrgcZnnbcFsoJukFAmKcwy8ACgkQZnnbcFsoJumQFAEAzh1HFd0+cHtIiKc6
          4t3HJOcGqbKbpg2gJUwquLY4/skBAJG8THl6PPpo3jQAU4a90PnlOajh2yOAa1hH
          mSbMbQoMwsBzBBABCgAdFiEEVCB28ErTW5q7AxeSqbZt2DI76ocFAmUcqr4ACgkQ
          qbZt2DI76oeKcwf8CV/oiS99aKHPSYSgS2JxAux5G//94J3G1wjRXs/Ijk7iSq6P
          K3tqugvBpfK8UPZG9RqRlRkaSnuodS5dZFOrBUOR5Xxb1vKiMK6TXuphSNhB18+o
          nMahDYJcVJQWsuW4ABj1pMLGdjjhg4CJwdxSlocZd1G79f1vqChMGXyHSXnIFz/3
          44hzxRb8vCkNt+0YqdSmk5kISdsKaej9VkpSKFbwqrMtbYLri2DPPOJ3j3fpOYYk
          dkmFmKsVQV2j/XlfbbbeirKUx8I/W+hF78g/R+kqw7csvzOLApY09/8IGib3QDOy
          YwCXmFgIr62Hx+FPRsBKvVfvx4usjV1iJ1MocM7BTQRYrdoqARAA53i/UvZuL4VN
          25WkY1VFMie2/6k43Espbwh+V1BOkdpPnJBGY3wDGTy6Tvv7RTNiSCTA+Eonyrkt
          8XJPSrWRgrnxpnMIi0Ec3hxe7yVCqyw+UU5DYtt8nb1mYD47cUPg009WXJ+wa0BW
          OhYJ0aFFSMcLXcNWzGP/Pa7BYEucMLjBEnd0NkWIG+xDhTqZ7sOnWu1mpFn+CIZx
          eZ7DWBg1WiB86Yqgpfrk239XqQo6zpSM5Gd2d2JOQjP04hcz5M9pS8/PXKQ/FPjb
          QrH2oFln43dlN4w2qYB/u50JwhFqUTrc2ihxupQN6V3YsecxvHkXOv9CG1Elr34y
          sSyz3zXgktqQi9yHhCOZ6LYRBGHUB+rM6S6IO/cQfXVZyciiW1X8V57HqGKla0c9
          lVW1COQZcJugeNBN3hlX1EForseeA7KclTDJONTMe0Cd4spyGtTeGQKlTABK7sl0
          0U8XPV1tLWIQzAP9RmL89BJhaZvC80xwOrBVbT5v2ZTQl+j9V8ycK7+w0kCg+hhp
          QUFF/jnhCfLU5JH/EEyUj1HYfD/GMQxUuRDhgL4YaTAWA+NpEKal4xAvl3MnE7xi
          O4pqYL/Tw2NUQgtc5AYyj2tdtKzYb/4ZFZP2IbhqGo6B8suIe2UKKXXDLaTdnYJo
          RHoJ8vSQksMX0JkNMytIO5ukh4ijMI8AEQEAAcLDfgQYAQgACQUCWK3aKgIbAgIp
          CRCNgYA8Dr/NiMFdIAQZAQgABgUCWK3aKgAKCRB+oKnD8nP82NVgD/9sCfkdIBOq
          rHHt642iM+fDyZnPIKCq4q+YZxJVoT4G6u3GCLFuaohci4ZHaWHDJoQ/ZkYj6UJ+
          mGtsN3twfM3yFSoqWzAZ5Hv8rWfTO6h5gwnI6IkpsBFzd8CmCJg/VRzjbJfwhta1
          PSLMNY7QeYNWMbgQOzP5t+lzesdrvjbTTAwfT+esnOIH7GVREigPb/smNv5eOS/H
          f1lJFItGF6Jp+ocgRiOyawS6tAl9+xhGD+jva6yoqX8+913zuySBszimZZY2/w/U
          V/4O50Wwp/txLR+8Z5Pkyv+dHrhCsPEjFINeO7CU3KUJr+lM2XDOCYC9B2x1QqI1
          eAv6ZRC8DHXQCzhXmEM04n+rDET3/tw0o/H62yJ4woQt8ji8tOm6/dihaJtexCI9
          ggHKHqu1D4YtqKLmAcD8YecrXXoSZKKPrDe0SFrmuj9lkpqJ+VPPPHEspVwtPgAx
          XYC1/Sts6w1WFBtb6PAl9L88RQWh8Dej8dun4SE9f4WFB0Edc1XzQ3MkJl6pDp2b
          76DH8/0NLPQYRSf81OgIEGyGRP4ZtbKbH4L7bA9X62X8oFyfX4qz/jEgCPNMR0n/
          dakkWTo+D5d2STW6uMmMb9G9aZDKnhnY3QmIS1Pi2eMG0JqQpElXtqa5S7q3ooF7
          ZmX5Knr0c+xayGYrvZMvMJwgD8Au/85ktfK4D/9e2zrS+P4iM0IcQAKADFlaxsiY
          r0pI4UhsdbgqI7Fn7EwJtdT+47K7iC+tWczFFRNmjNz5o+RvlvQHGefBJvtVrFZw
          F3VEf/2zJocq/MC/xtWDtVdyRCU0XcbEsXWGuHXhgQWPwHabMNuI8YTiUfpbCaai
          FHm/fffkfHrg4URxvXhTuw0busHmrVCerLrqaA00Vra/+MhqnnSsVd6kITS0p2gM
          6lv9ZwN4lAeJO5AmimcYXYQ2wpX/T9+6mkVuOuwSwlTv3KC98lZudHcHazbSqTAY
          d2aWwdbib4IvZl7cgTjCd7/EWXg8xYhvB3QrYPUbyLfwCBaB0R90vlO/TU+otCj8
          yyJg37PE+0ZacrjHOFH7PIIMoPb9wHunDd3kMsXCt8NHGwcLIf50DX7AOrrvvR+z
          YW3oQTIWJ6TWcqx8wps8l5GrsEQKqAmxgjcpE0cLLq/YEuNU0DPLLA9YxYXjiX94
          Tg55ClPhyo7zETpdQyu83Zi3TcwNXL7WR/5wgvSj49c/EAuO0scfnU2UseDjQIcG
          0vyzdz6CrZ/Cz42PTT/bg1iPk1mKrktlPihw6wQ5bIKMw27PzowsXKQ8zZl6VkBx
          LR1O+uPTlxz+1HjUk9ZglAh+anWp5NFdYnoxevwn0xVODH3KxmE/dKhRfdzN79NQ
          W8T/hCGNv/bYiD263cLDlQQYAQgACQUCWK3aKgIbAgJACRCNgYA8Dr/NiMFdIAQZ
          AQgABgUCWK3aKgAKCRB+oKnD8nP82NVgD/9sCfkdIBOqrHHt642iM+fDyZnPIKCq
          4q+YZxJVoT4G6u3GCLFuaohci4ZHaWHDJoQ/ZkYj6UJ+mGtsN3twfM3yFSoqWzAZ
          5Hv8rWfTO6h5gwnI6IkpsBFzd8CmCJg/VRzjbJfwhta1PSLMNY7QeYNWMbgQOzP5
          t+lzesdrvjbTTAwfT+esnOIH7GVREigPb/smNv5eOS/Hf1lJFItGF6Jp+ocgRiOy
          awS6tAl9+xhGD+jva6yoqX8+913zuySBszimZZY2/w/UV/4O50Wwp/txLR+8Z5Pk
          yv+dHrhCsPEjFINeO7CU3KUJr+lM2XDOCYC9B2x1QqI1eAv6ZRC8DHXQCzhXmEM0
          4n+rDET3/tw0o/H62yJ4woQt8ji8tOm6/dihaJtexCI9ggHKHqu1D4YtqKLmAcD8
          YecrXXoSZKKPrDe0SFrmuj9lkpqJ+VPPPHEspVwtPgAxXYC1/Sts6w1WFBtb6PAl
          9L88RQWh8Dej8dun4SE9f4WFB0Edc1XzQ3MkJl6pDp2b76DH8/0NLPQYRSf81OgI
          EGyGRP4ZtbKbH4L7bA9X62X8oFyfX4qz/jEgCPNMR0n/dakkWTo+D5d2STW6uMmM
          b9G9aZDKnhnY3QmIS1Pi2eMG0JqQpElXtqa5S7q3ooF7ZmX5Knr0c+xayGYrvZMv
          MJwgD8Au/85ktRYhBJ3IWCKfx904hUri2I2BgDwOv82I8rgP/17bOtL4/iIzQhxA
          AoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W9AcZ
          58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw24jx
          hOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqedKxV
          3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3yVm50
          dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHRH3S+
          U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh/nQN
          fsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQM8ss
          D1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47Sxx+d
          TZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/OjCxc
          pDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrGYT90
          qFF93M3v01BbxP+EIY2/9tiIPbrdwnUEEBYKAB0WIQRCDWaOM6uyhbM+uBxmedtw
          Wygm6QUCYpzDLwAKCRBmedtwWygm6ZAUAQDOHUcV3T5we0iIpzri3cck5wapspum
          DaAlTCq4tjj+yQEAkbxMeXo8+mjeNABThr3Q+eU5qOHbI4BrWEeZJsxtCgw=
          =cbSV
          -----END PGP PUBLIC KEY BLOCK-----
        mode: 644

    - name: docker-ce - create ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/docker-ce.list
        search_string: 'deb'
        line: 'deb https://download.docker.com/linux/ubuntu jammy stable'
        create: true
      when: not nexus

    - name: docker-ce - create ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/docker-ce.list
        search_string: 'deb'
        line: 'deb http://ubuntu-proxy:8081/repository/ubuntu-jammy-docker-ce jammy stable'
        create: true
      when: nexus

    - name: docker-ce - install
      ansible.builtin.apt:
        update_cache: true
        install_recommends: true
        state: latest
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

    - name: docker-ce - cleanup
      ansible.builtin.apt:
        autoremove: true
        autoclean: true

    - name: docker-ce - configure insecure registries
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
        force: yes
      when: nexus

    - name: docker-ce - gathering current environment
      ansible.builtin.stat:
        path: /home/.docker
      register: docker_home

    - name: docker-ce - stop service
      ansible.builtin.systemd:
        name: docker.service
        state: stopped
      when: not docker_home.stat.exists

    - name: docker-ce - move docker-data
      ansible.builtin.shell: mv /var/lib/docker/ /home/.docker/
      when: not docker_home.stat.exists

    - name: docker-ce - create symlinks
      ansible.builtin.file:
        src: /home/.docker/
        dest: /var/lib/docker
        state: link
      when: not docker_home.stat.exists

    - name: docker-ce - start service
      ansible.builtin.systemd:
        name: docker.service
        state: started
      when: not docker_home.stat.exists