#bfe001

- name: software from native sources
  ansible.builtin.apt:
    update_cache: true
    install_recommends: true
    pkg:
    - build-essential
    - cloc
    - cpp
    - fonts-jetbrains-mono
    - gcc
    - git
    - git-lfs
    - ldap-utils
    - nmap
    - postgresql-client
    - qemu-kvm
    - shim-signed
    - syslinux-common
  tags:
    - misc-from-native

- name: install ansible from ppa
  ansible.builtin.import_tasks: ppa-ansible-6.yml
  tags:
    - ppa-ansible-6

- name: add pipy-proxy
  ansible.builtin.import_tasks: pipy-proxy.yml
  tags:
    - pypi-proxy
    - mitogen
  when: nexus

- name: install mitogen
  ansible.builtin.import_tasks: ansible-mitogen.yml
  tags:
    - mitogen

- name: install golang from ppa
  ansible.builtin.import_tasks: ppa-golang.yml
  tags:
    - ppa-golang

- name: install docker-ce
  ansible.builtin.import_tasks: docker-ce.yml
  tags:
    - docker-ce

- name: install nodejs
  ansible.builtin.import_tasks: nodejs.yml
  tags:
    - nodejs

- name: install kubernetes tools
  ansible.builtin.import_tasks: kubernetes-tools.yml
  tags:
    - kubernetes-tools

- name: install commandline tools
  ansible.builtin.import_tasks: commandline-tools.yml
  tags:
    - commandline-tools

- name: install nvidia container toolkit
  ansible.builtin.import_tasks: nvidia-container-toolkit.yml
  tags:
    - nvidia-container-toolkit


    