- name: pipy-proxy - set hosts entry
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ pipy_proxy_ip }} {{ pipy_proxy }}"
    state: present
    when: pipy_proxy_use

- name: pipy-proxy - write config
  ansible.builtin.template:
    src: pip.conf.j2
    dest: /etc/pip.conf
    owner: root
    group: root
    mode: 0644
    force: yes
    when: pipy_proxy_use
