- name: install golang
  block:
    - name: ppa-golang - deploy ppa gpg key
      ansible.builtin.blockinfile:
        path: /etc/apt/trusted.gpg.d/ppa-golang-backports.asc
        create: true
        block: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Comment: Hostname: 
          Version: Hockeypuck 2.1.0-223-gdc2762b

          xo0ET551kQEEAME7Iyb7+c79CVWVwe+QaNlAVgauke1Q9Ycw8Rdxj55lKBJ5Ilpp
          LwiKreAVin4CCaGEtT9btePbYYKg8I+/dsiDbE9+o8e8FIMEBwy+FS+9bwLZ5WZP
          6nEtKPrrk3E+RUUpNbmO6udA62E0q2w7NcoA1jRS2YucsIL39aFXJcmvABEBAAHN
          IUxhdW5jaHBhZCBQUEEgZm9yIFNpbW9uIEVpc2VubWFubsK4BBMBAgAiBQJPnnWR
          AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRD2vIFzVqPUXle6BAC3FUrE
          7j4ltlgGAT2vRNlqWe8W6v0v20e1M8GsFHNB24zL/iRitUMosaWX94ufExwm+83y
          ka4Cq0J4oUCSJtgWDLb6K2hYMKLnofj889+4ZN0akNyMOg0O5usD0oJJuRXL0+e3
          sZo8b2aj7MwrHe+rTLLnlyKlRTUpt1gGF5GuiA==
          =iKVn
          -----END PGP PUBLIC KEY BLOCK-----
        mode: 644

    - name: ppa-golang - create ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/ubuntu-{{ ansible_lsb.codename }}-ppa-golang-backports.list
        search_string: 'deb'
        line: 'deb https://ppa.launchpadcontent.net/longsleep/golang-backports/ubuntu {{ ansible_lsb.codename }} main'
        create: true
      when: not nexus

    - name: ppa-golang - create ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/ubuntu-{{ ansible_lsb.codename }}-ppa-golang-backports.list
        search_string: 'deb'
        line: 'deb {{ nexus_proto }}://{{ nexus_host }}:{{ nexus_port }}/repository/ubuntu-{{ ansible_lsb.codename }}-ppa-golang-backports {{ ansible_lsb.codename }} main'
        create: true
      when: nexus

    - name: ppa-golang - install
      ansible.builtin.apt:
        update_cache: true
        install_recommends: true
        state: latest
        pkg:
          - "golang-{{ golang_version }}"
      register: golang_install

    - name: ppa-golang - remove existent exec symlink 
      ansible.builtin.file:
        path: /usr/local/sbin/go
        state: absent
      when: golang_install is changed
      ignore_errors: true

    - name: ppa-golang - create new exec symlink
      ansible.builtin.file:
        src: "/usr/lib/go-{{ golang_version }}/bin/go"
        dest: /usr/local/sbin/go
        state: link
      when: golang_install is changed

    - name: ppa-golang - cleanup
      ansible.builtin.apt:
        autoremove: true
        autoclean: true

    - name: ppa-golang - install language server fron native repos
      ansible.builtin.apt:
        update_cache: false
        install_recommends: true
        state: latest
        pkg:
          - gopls